addons:
  apt_packages:
    - lib32bz2-1.0
    - lib32ncurses5
    - lib32z1
install:
  - wget https://launchpad.net/gcc-arm-embedded/5.0/5-2016-q1-update/+download/gcc-arm-none-eabi-5_3-2016q1-20160330-linux.tar.bz2
  - tar -xf gcc-arm-none-eabi-5_3-2016q1-20160330-linux.tar.bz2
  - export PATH=$PATH:`pwd`/gcc-arm-none-eabi-5_3-2016q1/bin
script:
- make
